import type { RoadmapRequest } from "@/lib/roadmap/schema";
import type {
  GapAnalysis,
  GapCategory,
  GapItem,
  GapPriority,
  GapTimeHorizon,
  ReadinessGate,
  RatingScale,
  ResolvedCareer,
  TopMove,
} from "@/types";
import { formatGpa } from "@/lib/gpa";
import { resolvePlaybooksForCareers } from "@/lib/roadmap/playbooks";

/**
 * Deterministic gap analysis: compares the student's confirmed profile
 * against the target career's structured competitiveness data. This is
 * intentionally NOT generated by the AI — it's the authoritative, explainable
 * foundation that both the AI and fallback roadmap generators build on top of.
 *
 * Supports one or more target careers. When a student is aiming for
 * versatility across multiple paths, a gap that's relevant to more than one
 * of them (an "overlap" gap — a skill or cert valued across several target
 * careers) is the highest-leverage thing they can work on, since closing it
 * once pays off everywhere. Overlap gaps are surfaced with a boosted
 * priority/impact and every GapItem carries `relevantCareers` so the UI can
 * show exactly which target careers a given gap (or top move) advances.
 */

function normalize(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]/g, "");
}

/** Oxford-comma joiner for short lists, e.g. "Python, SQL, and Git". */
function joinNatural(items: string[]): string {
  if (items.length <= 1) return items[0] ?? "";
  if (items.length === 2) return `${items[0]} and ${items[1]}`;
  return `${items.slice(0, -1).join(", ")}, and ${items[items.length - 1]}`;
}

/** Avoids "FE Exam exam" when a credential's own name already ends in "Exam"/"Test". */
function withExamSuffix(credentialName: string): string {
  return /exam|test$/i.test(credentialName) ? credentialName : `${credentialName} exam`;
}

function fuzzyIncludes(haystack: string[], needle: string): boolean {
  const n = normalize(needle);
  return haystack.some((h) => {
    const normalizedH = normalize(h);
    return normalizedH.includes(n) || n.includes(normalizedH);
  });
}

function containsKeyword(text: string, keywords: string[]): boolean {
  const lower = text.toLowerCase();
  return keywords.some((k) => lower.includes(k));
}

const UPPERCLASS_STAGES = [
  "college-junior",
  "college-senior",
  "recent-college-grad-undecided",
  "graduate-student",
  "career-changer",
];

/**
 * Whether the student is close enough to a grad-school/licensing application
 * window for an upperclass-gated credential (LSAT, MCAT, FE Exam) to be a
 * realistic near-term priority. Unknown stage defaults to eligible — there's
 * no positive evidence it's premature, and hiding a genuinely relevant test
 * is worse than surfacing one slightly early.
 */
function hasUpperclassStanding(stage: string | null): boolean {
  return stage === null || UPPERCLASS_STAGES.includes(stage);
}

/**
 * Converts a credential's intrinsic readiness gate into a phase-placement
 * horizon for THIS student, given their stage. This is the core of the
 * temporal-proximity filter: it's what stops the FE Exam, MCAT, LSAT, or a
 * professional license from dominating Phase A just because the career data
 * says it's important, when the student either isn't eligible yet or the
 * credential structurally can't happen until much later regardless of stage.
 */
function timeHorizonForCredential(gate: ReadinessGate | undefined, stage: string | null): GapTimeHorizon {
  if (gate === "requires-program-completion") return "long-term";
  if (gate === "requires-upperclass-standing") return hasUpperclassStanding(stage) ? "near-term" : "long-term";
  return "immediate";
}

let gapCounter = 0;
function nextId(category: GapCategory): string {
  gapCounter += 1;
  return `${category}-${gapCounter}`;
}

/** All skill-like text across skills + experience/project bullets, for fuzzy "do they already have this" checks. */
function allDemonstratedSkillText(request: RoadmapRequest): string[] {
  const fromExperience = request.experience.flatMap((e) => [e.summary ?? "", ...e.bullets]);
  const fromProjects = request.projects.flatMap((p) => [p.summary ?? "", ...p.bullets, ...p.technologies]);
  return [...request.currentSkills, ...fromExperience, ...fromProjects];
}

function buildCurrentStateSummary(request: RoadmapRequest): string[] {
  const summary: string[] = [];

  const eduBits = [request.educationStage?.replace(/-/g, " "), request.major, request.school].filter(Boolean);
  summary.push(eduBits.length > 0 ? eduBits.join(" · ") : "Education details not yet provided");

  if (request.gpa.raw !== null) {
    summary.push(`GPA: ${formatGpa(request.gpa)}`);
  }

  summary.push(
    request.currentSkills.length > 0
      ? `Skills: ${request.currentSkills.slice(0, 6).join(", ")}`
      : "No skills listed yet",
  );

  const experienceBits = [];
  if (request.experience.length > 0) experienceBits.push(`${request.experience.length} experience entr${request.experience.length === 1 ? "y" : "ies"}`);
  if (request.projects.length > 0) experienceBits.push(`${request.projects.length} project(s)`);
  if (request.awards.length > 0) experienceBits.push(`${request.awards.length} award(s)`);
  if (request.certifications.length > 0) experienceBits.push(`${request.certifications.length} certification(s)`);
  summary.push(experienceBits.length > 0 ? experienceBits.join(", ") : "No experience, projects, awards, or certifications listed yet");

  return summary;
}

function academicGaps(request: RoadmapRequest, resolvedCareers: ResolvedCareer[]): GapItem[] {
  const gaps: GapItem[] = [];
  const titles = resolvedCareers.map((rc) => rc.title);
  const withCareer = resolvedCareers.filter((rc): rc is { title: string; career: NonNullable<ResolvedCareer["career"]> } => rc.career !== null);

  if (!request.major) {
    const majorsSample = [...new Set(withCareer.flatMap((rc) => rc.career.commonMajors))].slice(0, 6);
    gaps.push({
      id: nextId("academic"),
      category: "academic",
      title: "Declare a major or field of study",
      description: majorsSample.length > 0
        ? `Common majors across your target career${withCareer.length > 1 ? "s" : ""} include ${majorsSample.join(", ")}.`
        : "Declaring a specific major or field of study will sharpen every other recommendation.",
      priority: "medium",
      impact: 3,
      effort: 2,
      timeHorizon: "immediate",
      estimatedHours: 2,
      relevantCareers: titles,
      evidenceOfCompletion: "Your official declared major on file with the registrar, or an updated major on your resume",
      tacticalActions: [
        {
          title: "Book a 15-minute appointment with your academic advisor this week",
          detail: "An advisor can confirm which majors actually keep your timeline to graduation intact.",
          estimatedHours: 1,
          evidenceOfCompletion: "A confirmed advising appointment on your calendar, or notes from the meeting",
        },
        {
          title: majorsSample.length > 0 ? `Compare 2-3 candidate majors against ${joinNatural(majorsSample.slice(0, 3))}` : "Compare 2-3 candidate majors against what your target field actually requires",
          detail: "Narrowing to a short list you can defend beats agonizing over every option.",
          estimatedHours: 1,
          evidenceOfCompletion: "A short written comparison, even a few bullet points, of your top 2-3 options",
        },
      ],
    });
  } else {
    const unaligned = withCareer.filter((rc) => !fuzzyIncludes(rc.career.commonMajors, request.major));
    if (unaligned.length > 0) {
      const majorsSample = [...new Set(unaligned.flatMap((rc) => rc.career.commonMajors))].slice(0, 6);
      gaps.push({
        id: nextId("academic"),
        category: "academic",
        title: "Build proof of fit through electives, projects, and internships",
        description: `Common majors for ${unaligned.map((rc) => rc.title).join(", ")} ${unaligned.length > 1 ? "are" : "is"} ${majorsSample.join(", ")}. That doesn't rule you out, but it means electives, projects, and internships need to work harder to demonstrate fit.`,
        priority: "medium",
        impact: 3,
        effort: 3,
        timeHorizon: "immediate",
        estimatedHours: 15,
        relevantCareers: unaligned.map((rc) => rc.title),
        evidenceOfCompletion: `A transcript line, project, or internship you can point to that ties directly to ${joinNatural(unaligned.map((rc) => rc.title))}`,
        tacticalActions: [
          {
            title: `Pick one elective next term from ${majorsSample.length > 0 ? joinNatural(majorsSample.slice(0, 3)) : "your target field's core coursework"}`,
            detail: "One well-chosen elective on your transcript does more for credibility than a paragraph explaining your major.",
            estimatedHours: 2,
            evidenceOfCompletion: "The elective showing on your registered course schedule",
          },
          {
            title: `Start a small project that uses a core skill from ${joinNatural(unaligned.map((rc) => rc.title))}`,
            detail: "A project is the fastest way to prove capability that your major doesn't already signal.",
            estimatedHours: 10,
            evidenceOfCompletion: "A GitHub repo or write-up you can link from your resume",
          },
          {
            title: "Rewrite your resume summary to connect your coursework directly to your target field",
            detail: "Recruiters skimming your resume need the connection spelled out, not implied.",
            estimatedHours: 3,
            evidenceOfCompletion: "An updated resume summary line naming the specific connection",
          },
        ],
      });
    }
  }

  const advancedCareers = withCareer.filter((rc) => rc.career.advancedDegreeTypical);
  if (advancedCareers.length > 0) {
    const mentionsGradSchool = containsKeyword(request.careerGoals, ["grad school", "graduate school", "master", "phd", "md", "pharmd", "j.d.", "jd", "law school"]);
    if (!mentionsGradSchool && request.educationStage !== "graduate-student") {
      // Different graduate paths gate on different admissions tests — the
      // playbook resolver is what stops a pre-law or pre-med student from
      // being told to study for the GRE.
      const playbooks = resolvePlaybooksForCareers(advancedCareers);
      const gatingPlaybook = playbooks.find((p) => p.gatingExam !== null);
      const admissionsTest = gatingPlaybook?.gatingExam ?? "GRE or required subject test";
      const timeHorizon = timeHorizonForCredential(gatingPlaybook?.gatingExamReadiness, request.educationStage);
      const isLaw = advancedCareers.some((rc) => rc.career.category === "law");
      const isHealthcare = advancedCareers.some((rc) => rc.career.category === "healthcare");
      const planTitle = isLaw ? "Map out your law school plan" : isHealthcare ? "Map out your medical/graduate school plan" : "Map out your graduate school plan";
      gaps.push({
        id: nextId("academic"),
        category: "academic",
        title: planTitle,
        description: advancedCareers.map((rc) => rc.career.graduateSchoolConsiderations).join(" "),
        priority: "high",
        impact: 4,
        effort: 4,
        timeHorizon,
        estimatedHours: 20,
        relevantCareers: advancedCareers.map((rc) => rc.title),
        evidenceOfCompletion: `A shortlist of 3-5 target programs, ${/^[aeiou]/i.test(admissionsTest) ? "an" : "a"} ${admissionsTest} test date, and an email sent to at least one professor or admissions contact of interest`,
        tacticalActions: [
          {
            title: "Research 5 graduate programs and shortlist your top 3",
            detail: "Filter on advisor fit and funding, not just program prestige.",
            estimatedHours: 4,
            evidenceOfCompletion: "A shortlist doc with program name, advisor of interest, and funding notes for each",
          },
          {
            title: `Register for and study for the ${admissionsTest}`,
            detail: "Most programs still weight this more than students expect, even when they call it optional.",
            estimatedHours: 12,
            evidenceOfCompletion: "A test registration confirmation and a score report once you've taken it",
          },
          {
            title: "Email one professor of interest at each shortlisted program",
            detail: "A specific, informed email referencing their actual work gets replies; a generic one doesn't.",
            estimatedHours: 2,
            evidenceOfCompletion: "Sent emails, ideally with at least one reply, in your inbox",
          },
          {
            title: "Draft a one-paragraph statement of purpose",
            detail: "Getting a rough draft down early gives you months to sharpen it instead of scrambling before deadlines.",
            estimatedHours: 2,
            evidenceOfCompletion: "A saved draft statement of purpose, even a rough one",
          },
        ],
      });
    }
  }

  return gaps;
}

/**
 * Round-robins single-career items (one skill belongs to exactly one
 * career's Set) across their careers, so a top-N slice can't be entirely
 * dominated by whichever career's items happened to sort first — every
 * target career gets fair representation among non-overlapping gaps.
 */
function pickFairly<T extends { careers: Set<string> }>(items: T[]): T[] {
  const byCareer = new Map<string, T[]>();
  for (const item of items) {
    const careerTitle = [...item.careers][0];
    const queue = byCareer.get(careerTitle) ?? [];
    queue.push(item);
    byCareer.set(careerTitle, queue);
  }

  const queues = [...byCareer.values()];
  const result: T[] = [];
  let index = 0;
  while (result.length < items.length) {
    const queue = queues[index % queues.length];
    const next = queue.shift();
    if (next) result.push(next);
    index++;
    if (queues.every((q) => q.length === 0)) break;
  }
  return result;
}

function technicalGaps(request: RoadmapRequest, resolvedCareers: ResolvedCareer[]): GapItem[] {
  const gaps: GapItem[] = [];
  const withCareer = resolvedCareers.filter((rc): rc is { title: string; career: NonNullable<ResolvedCareer["career"]> } => rc.career !== null);
  const titles = resolvedCareers.map((rc) => rc.title);

  if (withCareer.length === 0) {
    // Every target career is free-text/unrecognized ("Other / not listed"),
    // so there's no structured skill or cert data to diff against. Rather
    // than silently returning zero technical gaps, give the student a real,
    // concrete research task so this path never looks like an empty/broken
    // roadmap just because their career wasn't in the curated dataset yet.
    if (titles.length === 0) return gaps;
    gaps.push({
      id: nextId("technical"),
      category: "technical",
      title: `Identify the specific skills ${joinNatural(titles)} actually rewards`,
      description: `"${joinNatural(titles)}" isn't in our curated career database yet, so we can't compare your skills against a structured list the way we do for recognized careers. Real job postings and working professionals are the fastest way to find out what's actually screened for.`,
      priority: "medium",
      impact: 3,
      effort: 2,
      timeHorizon: "immediate",
      estimatedHours: 5,
      relevantCareers: titles,
      evidenceOfCompletion: "A written list of 3-5 specific skills or tools pulled directly from real job postings for this career",
      tacticalActions: [
        {
          title: `Read 8-10 real job postings for ${joinNatural(titles)} and list the skills that show up repeatedly`,
          detail: "Real postings tell you what's actually screened for, more reliably than general career advice.",
          estimatedHours: 2,
          evidenceOfCompletion: "A written list of the skills and tools that appeared most often",
        },
        {
          title: "Find any certification or credential commonly listed in those postings and decide if it's worth pursuing",
          detail: "Not every listed certification is worth chasing, but knowing which ones actually show up matters.",
          estimatedHours: 2,
          evidenceOfCompletion: "A short note on which certification, if any, you're pursuing and why",
        },
        {
          title: "Start building one piece of evidence, a project, writing sample, or credential, toward the top skill you identified",
          detail: "Turning the research into a concrete next step is what actually closes the gap.",
          estimatedHours: 1,
          evidenceOfCompletion: "A started project, writing sample, or credential tied directly to the top skill you found",
        },
      ],
    });
    return gaps;
  }

  const demonstrated = allDemonstratedSkillText(request);

  const skillMap = new Map<string, { skill: string; careers: Set<string> }>();
  for (const { title, career } of withCareer) {
    for (const skill of career.highValueSkills) {
      if (fuzzyIncludes(demonstrated, skill)) continue;
      const key = normalize(skill);
      const entry = skillMap.get(key) ?? { skill, careers: new Set<string>() };
      entry.careers.add(title);
      skillMap.set(key, entry);
    }
  }

  const missingSkills = [...skillMap.values()].sort((a, b) => b.careers.size - a.careers.size);
  if (missingSkills.length > 0) {
    const overlapping = missingSkills.filter((s) => s.careers.size > 1);
    const top = [...overlapping, ...pickFairly(missingSkills.filter((s) => s.careers.size === 1))].slice(0, 4);
    const relevantCareers = [...new Set(top.flatMap((s) => [...s.careers]))];
    const topSkillNames = top.map((s) => s.skill);

    gaps.push({
      id: nextId("technical"),
      category: "technical",
      title: overlapping.length > 0
        ? `Build the skills that boost every target career at once: ${joinNatural(overlapping.slice(0, 3).map((s) => s.skill))}`
        : `Learn ${joinNatural(topSkillNames)}`,
      description: overlapping.length > 0
        ? `${joinNatural(overlapping.slice(0, 3).map((s) => s.skill))} ${overlapping.length === 1 ? "is" : "are"} valued by more than one of your target careers, so building ${overlapping.length === 1 ? "it" : "these"} once pays off across your whole versatility strategy, not just one path.`
        : `${top[0].careers.size > 1 ? "These" : `${top[0].skill} and similar skills`} are expected for ${joinNatural([...new Set(top.flatMap((s) => [...s.careers]))])}.`,
      priority: overlapping.length > 0 ? "high" : missingSkills.length >= 3 ? "high" : "medium",
      impact: overlapping.length > 0 ? 5 : 4,
      effort: 4,
      timeHorizon: "immediate",
      estimatedHours: top.length * 15,
      relevantCareers,
      evidenceOfCompletion: `A finished project, writing sample, or completed course module that puts ${joinNatural(topSkillNames)} to visible use (a GitHub repo for coding skills, a memo or brief for legal/policy writing, a case study for business/strategy skills)`,
      tacticalActions: topSkillNames.map((skill) => ({
        title: `Complete a focused mini-project or course module in ${skill}`,
        detail: `Hands-on practice with ${skill} beats reading about it. Pick one small, finishable build rather than an open-ended tutorial series.`,
        estimatedHours: 15,
        evidenceOfCompletion: `A committed project or completed course module specifically demonstrating ${skill}`,
      })),
    });
  }

  const certNames = request.certifications.map((c) => c.name);
  const certMap = new Map<string, { name: string; careers: Set<string>; reasoning: string; readinessGate?: ReadinessGate }>();
  for (const { title, career } of withCareer) {
    for (const cert of career.certifications) {
      if (!cert.recommend || fuzzyIncludes(certNames, cert.name)) continue;
      const key = normalize(cert.name);
      const entry = certMap.get(key) ?? { name: cert.name, careers: new Set<string>(), reasoning: cert.reasoning, readinessGate: cert.readinessGate };
      entry.careers.add(title);
      certMap.set(key, entry);
    }
  }

  const rankedCerts = [...certMap.values()].sort((a, b) => b.careers.size - a.careers.size);
  if (rankedCerts.length > 0) {
    const cert = rankedCerts[0];
    gaps.push({
      id: nextId("technical"),
      category: "technical",
      title: `Clear ${cert.name}`,
      description: cert.careers.size > 1
        ? `${cert.name} is valued across ${cert.careers.size} of your target careers (${[...cert.careers].join(", ")}). ${cert.reasoning}`
        : cert.reasoning,
      priority: "low",
      impact: cert.careers.size > 1 ? 4 : 3,
      effort: 3,
      timeHorizon: timeHorizonForCredential(cert.readinessGate, request.educationStage),
      estimatedHours: 25,
      relevantCareers: [...cert.careers],
      evidenceOfCompletion: `Your ${withExamSuffix(cert.name)} registration confirmation now, and the certificate itself once you pass`,
      tacticalActions: [
        {
          title: `Register for the ${withExamSuffix(cert.name)} and set a target date`,
          detail: "A real date on the calendar is what turns 'someday' into an actual study schedule.",
          estimatedHours: 1,
          evidenceOfCompletion: "Your exam registration confirmation email",
        },
        {
          title: "Work through the official study guide or a structured prep course",
          detail: "Use the official materials first; third-party crash courses are a poor substitute for the real content outline.",
          estimatedHours: 18,
          evidenceOfCompletion: "Completed chapters or modules checked off in the study guide/course",
        },
        {
          title: "Take 2-3 full-length practice tests under timed conditions",
          detail: "Practice tests are the single best predictor of whether you're actually ready.",
          estimatedHours: 6,
          evidenceOfCompletion: "Practice test scores showing improvement across attempts",
        },
      ],
    });
  }

  return gaps;
}

function experienceGaps(request: RoadmapRequest, resolvedCareers: ResolvedCareer[]): GapItem[] {
  const gaps: GapItem[] = [];
  const titles = resolvedCareers.map((rc) => rc.title);
  const withCareer = resolvedCareers.filter((rc): rc is { title: string; career: NonNullable<ResolvedCareer["career"]> } => rc.career !== null);

  const strongExpectation = (text: string) =>
    containsKeyword(text, ["essential", "mandatory", "close to", "strongly", "extremely important"]);

  if (request.experience.length === 0) {
    const criticalCareers = withCareer.filter((rc) => strongExpectation(rc.career.internshipExpectations));
    const priority: GapPriority = criticalCareers.length > 0 ? "critical" : "high";
    const description = withCareer.length === 1
      ? withCareer[0].career.internshipExpectations
      : withCareer.length > 1
        ? `Internships (or equivalent hands-on experience) are expected across your target careers, especially ${(criticalCareers.length > 0 ? criticalCareers : withCareer).map((rc) => rc.title).join(", ")}.`
        : "Internships (or equivalent hands-on experience) are one of the strongest signals employers look for.";

    gaps.push({
      id: nextId("experience"),
      category: "experience",
      title: "Land an internship or hands-on role",
      description,
      priority,
      impact: 5,
      effort: 4,
      timeHorizon: "immediate",
      estimatedHours: 120,
      relevantCareers: titles,
      evidenceOfCompletion: "An offer letter, a LinkedIn experience entry, or your name on an employer or lab roster",
      tacticalActions: [
        {
          title: "Build a target list of 20+ employers (companies, firms, or labs) and set up alerts on Handshake and LinkedIn",
          detail: "A specific target list beats scrolling job boards aimlessly.",
          estimatedHours: 5,
          evidenceOfCompletion: "A saved list of target employers with active job alerts running",
        },
        {
          title: "Tailor your resume and write a specific cover letter for your first 10 applications",
          detail: "Generic applications get filtered out before a human ever reads them.",
          estimatedHours: 15,
          evidenceOfCompletion: "10 tailored resume/cover letter pairs, one per target role",
        },
        {
          title: "Apply to at least 20 positions in weekly batches",
          detail: "Steady weekly output compounds; one big application weekend usually doesn't.",
          estimatedHours: 20,
          evidenceOfCompletion: "An applications tracker showing 20+ submitted applications",
        },
        {
          title: "Run mock interviews and drill practice problems for your target role type",
          detail: "This is where most candidates lose offers despite having the right resume.",
          estimatedHours: 60,
          evidenceOfCompletion: "Completed mock interview sessions and a practice-problem log",
        },
        {
          title: "Follow up on every application after 1-2 weeks of silence",
          detail: "A short, polite follow-up regularly moves an application off the pile.",
          estimatedHours: 20,
          evidenceOfCompletion: "Follow-up emails sent, logged in your applications tracker",
        },
      ],
    });
  }

  if (request.projects.length === 0) {
    const portfolioHeavyCareers = withCareer.filter((rc) => rc.career.codingIntensity >= 4 || rc.career.handsOnIntensity >= 4);
    const writingHeavyCareers = withCareer.filter((rc) => rc.career.communicationIntensity >= 4 && rc.career.codingIntensity < 4 && rc.career.handsOnIntensity < 4);
    const description = withCareer.length === 1
      ? withCareer[0].career.portfolioExpectations
      : withCareer.length > 1
        ? "A concrete work sample you can explain in depth is one of the fastest ways to stand out, and one that draws on skills shared across your target careers demonstrates versatility directly."
        : "A concrete work sample you can explain in depth is one of the fastest ways to stand out.";

    if (portfolioHeavyCareers.length > 0 || writingHeavyCareers.length === 0) {
      gaps.push({
        id: nextId("experience"),
        category: "experience",
        title: "Build a portfolio project",
        description,
        priority: portfolioHeavyCareers.length > 0 ? "high" : "medium",
        impact: 4,
        effort: 3,
        timeHorizon: "immediate",
        estimatedHours: 30,
        relevantCareers: titles,
        evidenceOfCompletion: "A live GitHub repo with a real README, plus a deployed demo link on Vercel, Streamlit Community Cloud, or Netlify if it's shippable",
        tacticalActions: [
          {
            title: "Pick one real, specific problem to solve, not a tutorial clone",
            detail: "A project that solves something you actually ran into is easier to talk about convincingly in an interview.",
            estimatedHours: 2,
            evidenceOfCompletion: "A one-paragraph project spec you wrote yourself",
          },
          {
            title: "Build the core functionality end-to-end before polishing anything",
            detail: "A rough but complete build beats a polished half-finished one every time.",
            estimatedHours: 20,
            evidenceOfCompletion: "A working end-to-end version, even if the UI is rough",
          },
          {
            title: "Write a clear README and deploy a live demo",
            detail: "A recruiter will look for 60 seconds; make those seconds count.",
            estimatedHours: 5,
            evidenceOfCompletion: "A README with a live demo link, both working",
          },
          {
            title: "Get feedback from one person outside your head and iterate once",
            detail: "You're too close to your own project to see what's confusing about it.",
            estimatedHours: 3,
            evidenceOfCompletion: "Notes from the feedback session and at least one change made in response",
          },
        ],
      });
    } else {
      gaps.push({
        id: nextId("experience"),
        category: "experience",
        title: "Produce a polished work sample",
        description,
        priority: "high",
        impact: 4,
        effort: 3,
        timeHorizon: "immediate",
        estimatedHours: 25,
        relevantCareers: titles,
        evidenceOfCompletion: "A polished writing sample, memo, brief, or case study you can send directly to an employer or attach to an application",
        tacticalActions: [
          {
            title: "Pick one real, specific issue or case to analyze, not a generic overview",
            detail: "A piece that takes a clear position on something real is far more convincing than a broad summary of a topic.",
            estimatedHours: 2,
            evidenceOfCompletion: "A one-paragraph outline of your position and argument",
          },
          {
            title: "Write a full first draft end-to-end before polishing anything",
            detail: "A complete, rough draft beats a polished, half-finished one every time.",
            estimatedHours: 12,
            evidenceOfCompletion: "A complete first draft, even if the phrasing is still rough",
          },
          {
            title: "Revise for clarity and cut anything that doesn't support your argument",
            detail: "A reader will spend a minute deciding if this is worth their time; make that minute count.",
            estimatedHours: 6,
            evidenceOfCompletion: "A tightened final draft with a clear thesis and structure",
          },
          {
            title: "Get feedback from one person outside your head and revise once",
            detail: "You're too close to your own writing to see what's unclear or unconvincing.",
            estimatedHours: 3,
            evidenceOfCompletion: "Notes from the feedback session and at least one revision made in response",
          },
        ],
      });
    }
  }

  const researchCareers = withCareer.filter((rc) => rc.career.researchIntensity >= 4 && strongExpectation(rc.career.researchExpectations));
  if (researchCareers.length > 0) {
    const researchText = [
      ...request.projects.flatMap((p) => [p.title, p.summary ?? "", ...p.bullets]),
      ...request.experience.flatMap((e) => [e.title ?? "", e.summary ?? "", ...e.bullets]),
      request.careerGoals,
    ].join(" ");
    if (!containsKeyword(researchText, ["research"])) {
      gaps.push({
        id: nextId("experience"),
        category: "experience",
        title: "Get involved in research",
        description: researchCareers.map((rc) => rc.career.researchExpectations).join(" "),
        priority: "medium",
        impact: 4,
        effort: 4,
        timeHorizon: "immediate",
        estimatedHours: 60,
        relevantCareers: researchCareers.map((rc) => rc.title),
        evidenceOfCompletion: "Your name on a lab website, an email from a PI confirming your role, or an authorship/acknowledgment on a paper or poster",
        tacticalActions: [
          {
            title: "Identify 3-5 labs doing work relevant to your target field and read one recent paper from each",
            detail: "You need a genuine, specific reason to reach out, not just 'I'm interested in research.'",
            estimatedHours: 8,
            evidenceOfCompletion: "Notes on 3-5 labs, each with a specific paper or project you can reference",
          },
          {
            title: "Email each lab with a specific, informed question about their work",
            detail: "PIs get generic requests constantly; referencing their actual paper is what gets a reply.",
            estimatedHours: 2,
            evidenceOfCompletion: "Sent emails, ideally with at least one reply",
          },
          {
            title: "Complete an onboarding task or literature review if accepted into a lab",
            detail: "Most labs start new members on a small, low-risk task before trusting them with real work.",
            estimatedHours: 30,
            evidenceOfCompletion: "A completed literature review or onboarding deliverable you can show",
          },
          {
            title: "Contribute to an ongoing project or propose a small supervised mini-project",
            detail: "This is the step that turns 'I emailed a professor' into an actual research credential.",
            estimatedHours: 20,
            evidenceOfCompletion: "A specific contribution you can name and describe in an interview",
          },
        ],
      });
    }
  }

  return gaps;
}

function professionalGaps(request: RoadmapRequest, resolvedCareers: ResolvedCareer[]): GapItem[] {
  const titles = resolvedCareers.map((rc) => rc.title);
  const playbooks = resolvePlaybooksForCareers(resolvedCareers);
  // Concrete role/focus phrasing beats generic "network with X" filler —
  // e.g. "reach out to firm associates... focusing on litigation practices"
  // instead of "network with lawyers".
  const roles = playbooks.length > 0 ? joinNatural(playbooks.map((p) => p.networkingTemplate.roles)) : null;
  const focusAreas = playbooks.length > 0 ? joinNatural(playbooks.map((p) => p.networkingTemplate.focusAreas)) : null;

  const gaps: GapItem[] = [
    {
      id: nextId("professional"),
      category: "professional",
      title: roles
        ? `Line up 2 to 3 informational interviews with ${roles}, focusing on ${focusAreas}`
        : titles.length > 0
          ? `Line up 2 to 3 informational chats with people working as a ${titles.join(" or a ")}`
          : "Line up 2 to 3 informational chats with people in your target field",
      description: roles
        ? `Talking directly to ${roles} about ${focusAreas} is one of the highest-leverage, lowest-cost moves available.`
        : titles.length > 0
          ? `Talking directly to people working as a ${titles.join(" or a ")} is one of the highest-leverage, lowest-cost moves available.`
          : "Talking directly to people in your target field is one of the highest-leverage, lowest-cost moves available.",
      priority: "medium",
      impact: 3,
      effort: 2,
      timeHorizon: "near-term",
      estimatedHours: 5,
      relevantCareers: titles,
      evidenceOfCompletion: "A LinkedIn connection accepted, a calendar invite that happened, or notes from the conversation you can reference in an interview",
      tacticalActions: [
        {
          title: roles ? `Find 5-8 ${roles} on LinkedIn, prioritizing ${focusAreas}` : titles.length > 0 ? `Find 5-8 people on LinkedIn currently working as a ${titles.join(" or a ")}` : "Find 5-8 people on LinkedIn currently working in your target field",
          detail: "Search alumni from your school first; they're the most likely to respond.",
          estimatedHours: 1,
          evidenceOfCompletion: "A saved list of 5-8 names with LinkedIn profile links",
        },
        {
          title: "Send each a short, specific connection message referencing their actual work",
          detail: "A message that mentions a specific project or post they wrote gets replies; a copy-pasted template doesn't.",
          estimatedHours: 1,
          evidenceOfCompletion: "Sent connection requests with personalized notes",
        },
        {
          title: "Prepare 3-4 real questions before each call",
          detail: "Specific questions about their day-to-day get you far more useful answers than 'any advice for someone starting out?'",
          estimatedHours: 1,
          evidenceOfCompletion: "A written question list for each scheduled conversation",
        },
        {
          title: "Have 2-3 conversations and send a genuine thank-you follow-up",
          detail: "The follow-up is what turns a one-time chat into an actual relationship you can go back to.",
          estimatedHours: 2,
          evidenceOfCompletion: "Completed calls plus sent thank-you messages referencing something specific they said",
        },
      ],
    },
  ];

  if (!request.careerGoals) {
    gaps.push({
      id: nextId("professional"),
      category: "professional",
      title: "Write down a specific career goal",
      description: "A specific, articulated goal makes your applications, interviews, and networking conversations sharper.",
      priority: "low",
      impact: 2,
      effort: 1,
      timeHorizon: "immediate",
      estimatedHours: 1,
      relevantCareers: titles,
      evidenceOfCompletion: "A one-paragraph goal statement saved in your PathFinder profile and at the top of your resume draft",
      tacticalActions: [
        {
          title: "Draft a one-paragraph goal answering what role, why it, and by when",
          detail: "Specificity is what makes a goal usable in applications and interviews instead of just a nice sentiment.",
          estimatedHours: 1,
          evidenceOfCompletion: "A saved one-paragraph goal statement",
        },
      ],
    });
  }

  return gaps;
}

export function analyzeGaps(request: RoadmapRequest, resolvedCareers: ResolvedCareer[]): GapAnalysis {
  const gaps = [
    ...academicGaps(request, resolvedCareers),
    ...technicalGaps(request, resolvedCareers),
    ...experienceGaps(request, resolvedCareers),
    ...professionalGaps(request, resolvedCareers),
  ];

  return {
    currentStateSummary: buildCurrentStateSummary(request),
    targetCareers: resolvedCareers.map((rc) => rc.title),
    gaps,
  };
}

const PRIORITY_RANK: Record<GapPriority, number> = { critical: 4, high: 3, medium: 2, low: 1 };

export function deriveTopMoves(gapAnalysis: GapAnalysis): TopMove[] {
  const ranked = [...gapAnalysis.gaps].sort((a, b) => {
    const priorityDiff = PRIORITY_RANK[b.priority] - PRIORITY_RANK[a.priority];
    if (priorityDiff !== 0) return priorityDiff;
    const overlapDiff = b.relevantCareers.length - a.relevantCareers.length;
    if (overlapDiff !== 0) return overlapDiff;
    const impactDiff = b.impact - a.impact;
    if (impactDiff !== 0) return impactDiff;
    return a.effort - b.effort;
  });

  return ranked.slice(0, 3).map((gap, index) => ({
    id: `top-move-${index + 1}`,
    title: gap.title,
    impact: gap.impact as RatingScale,
    effort: gap.effort as RatingScale,
    estimatedHours: gap.estimatedHours,
    why: gap.description,
    relevantCareers: gap.relevantCareers,
  }));
}
