"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { RefreshCw } from "lucide-react";
import { APPLICATION_STATUS_LABELS } from "@/components/applications/application-form";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ProgressBar } from "@/components/ui/progress-bar";
import { Spinner } from "@/components/ui/spinner";
import { getAnalyticsOverview } from "@/services/analytics-service";
import type { DashboardOverview } from "@/types";

export function ProgressAnalytics() {
  const [data, setData] = useState<DashboardOverview | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setData(await getAnalyticsOverview()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load progress."); } finally { setLoading(false); } }, []);
  useEffect(() => {
    let cancelled = false;
    getAnalyticsOverview().then((next) => { if (!cancelled) setData(next); }).catch((cause) => { if (!cancelled) setError(cause instanceof Error ? cause.message : "Could not load progress."); }).finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, []);
  if (loading) return <div className="flex justify-center py-24"><Spinner className="h-6 w-6" /><span className="sr-only">Loading progress analytics</span></div>;
  if (error) return <div role="alert" className="mx-auto mt-12 max-w-2xl rounded-lg border border-danger/30 bg-danger-bg p-6"><h1 className="font-semibold text-danger">Progress analytics unavailable</h1><p className="mt-2 text-sm text-danger">{error}</p><Button className="mt-4" variant="outline" onClick={load}><RefreshCw className="h-4 w-4" />Retry</Button></div>;
  if (!data) return <div className="mx-auto max-w-2xl px-6 py-16 text-center"><h1 className="text-2xl font-semibold">Complete onboarding to start tracking progress</h1><Link href="/onboarding"><Button className="mt-5">Start onboarding</Button></Link></div>;
  return <div className="mx-auto max-w-6xl px-4 py-10 sm:px-6 sm:py-14"><p className="text-sm font-medium text-primary">Progress analytics</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">What is actually improving</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">{data.historyNote}</p>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric title="Readiness" value={data.readiness === null ? "—" : `${data.readiness}%`} detail={`${data.readinessHistory.length} recorded change${data.readinessHistory.length === 1 ? "" : "s"}`} /><Metric title="Skills improved" value={String(data.skillsImproved)} detail="Beyond initial exposure" /><Metric title="Assessments" value={String(data.assessmentsCompleted)} detail="Completed attempts" /><Metric title="Roadmap" value={`${data.roadmap.percent}%`} detail={`${data.roadmap.completed} of ${data.roadmap.total} tasks`} /></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Readiness over time</CardTitle><CardDescription>Only recorded readiness recalculations.</CardDescription></CardHeader><CardContent>{data.readinessHistory.length > 1 ? <div className="flex h-44 items-end gap-2" role="img" aria-label={`Readiness changed from ${data.readinessHistory[0].value} to ${data.readinessHistory.at(-1)!.value} percent`} >{data.readinessHistory.map((point) => <div key={point.date} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="text-xs font-medium">{point.value}%</span><div className="w-full rounded-t bg-primary" style={{ height: `${Math.max(point.value, 4)}%` }} /><span className="sr-only">{new Date(point.date).toLocaleDateString()}</span></div>)}</div> : <Empty>No readiness trend yet. Recompute your roadmap after meaningful profile or evidence changes.</Empty>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Assessment scores</CardTitle><CardDescription>Scores returned by completed evaluations; unavailable evaluations remain honest nulls.</CardDescription></CardHeader><CardContent>{data.assessmentScores.length ? <ul className="space-y-4">{data.assessmentScores.slice(-6).reverse().map((score) => <li key={`${score.date}-${score.skill}`}><div className="mb-1 flex justify-between text-sm"><span>{score.skill} · {score.stage}</span><strong>{score.score === null ? "Not evaluated" : `${score.score}%`}</strong></div>{score.score !== null && <ProgressBar value={score.score} />}</li>)}</ul> : <Empty>No completed assessments yet.</Empty>}</CardContent></Card></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Applications by stage</CardTitle><CardDescription>Current pipeline, not a fabricated historical funnel.</CardDescription></CardHeader><CardContent><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{Object.entries(data.applicationsByStage).map(([stage, count]) => <div key={stage} className="rounded-md bg-surface p-3"><p className="text-xl font-semibold">{count}</p><p className="text-xs text-muted-foreground">{APPLICATION_STATUS_LABELS[stage as keyof typeof APPLICATION_STATUS_LABELS]}</p></div>)}</div></CardContent></Card>
      <Card><CardHeader><CardTitle>Saved-job fit distribution</CardTitle><CardDescription>Latest fit analysis per one of your own saved jobs.</CardDescription></CardHeader><CardContent><div className="space-y-4">{([['High fit', data.savedJobFitDistribution.high, 'bg-success'], ['Medium fit', data.savedJobFitDistribution.medium, 'bg-warning'], ['Low fit', data.savedJobFitDistribution.low, 'bg-danger']] as const).map(([label, count, color]) => <div key={label} className="flex items-center justify-between rounded-md bg-surface p-3"><span className="flex items-center gap-2 text-sm"><span className={`h-2.5 w-2.5 rounded-full ${color}`} />{label}</span><strong>{count}</strong></div>)}</div></CardContent></Card></div>
    <Card className="mt-6"><CardHeader><CardTitle>Recurring missing requirements</CardTitle><CardDescription>Based only on your {data.savedJobCount} saved jobs—not global labor-market research.</CardDescription></CardHeader><CardContent>{data.recurringMissingRequirements.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.recurringMissingRequirements.map((skill) => <div key={skill.skill} className="rounded-md border border-border p-4"><div className="flex items-start justify-between gap-2"><p className="font-medium">{skill.skill}</p><Badge variant="accent">{skill.evidence}</Badge></div><p className="mt-2 text-sm text-muted-foreground">Seen in {skill.frequencyPercent}% · required in {skill.requiredFrequencyPercent}%</p></div>)}</div> : <Empty>Analyze saved jobs to identify recurring gaps.</Empty>}</CardContent></Card>
  </div>;
}
function Metric({ title, value, detail }: { title: string; value: string; detail: string }) { return <Card><CardHeader><CardTitle className="text-sm text-muted-foreground">{title}</CardTitle></CardHeader><CardContent><p className="text-3xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></CardContent></Card>; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="rounded-md border border-dashed border-border p-6 text-sm text-muted-foreground">{children}</p>; }
